name: Update Peningkatan

on:
  schedule:
    - cron: "*/10 * * * *" #run every 10 minutes

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1

      - name: Install dependencies
        run: |
          pip install requests
          pip install datetime
          pip install cloudscraper                  
      - name: Execute Script
        run: |
          python ini_tes.py